apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plant-backend.fullname" . }}-secret
  labels:
    {{- include "plant-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  TREFLE_API_TOKEN: {{ .Values.apis.trefleToken | b64enc | quote }}
  PERENUAL_API_KEY: {{ .Values.apis.perenualKey | b64enc | quote }}
  GEMINI_API_KEY: {{ .Values.apis.geminiKey | b64enc | quote }}
  OPENWEATHER_API_KEY: {{ .Values.apis.openweatherKey | b64enc | quote }}
  MCP_API_KEY: {{ .Values.mcp.apiKey | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc | quote }}
