stages:
  - test
  - build

variables:
  KUBE_NAMESPACE: plant-manager
  HTTP_PROXY: "http://cache-etu.univ-artois.fr:3128"
  HTTPS_PROXY: "http://cache-etu.univ-artois.fr:3128"
  http_proxy: "http://cache-etu.univ-artois.fr:3128"
  https_proxy: "http://cache-etu.univ-artois.fr:3128"
  NO_PROXY: "localhost,127.0.0.1"

default:
  tags:
    - k8s-etu

# ==================== TEST ====================
test:
  stage: test
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - flutter pub get
    - flutter analyze --no-fatal-infos --no-fatal-warnings
    - flutter test --no-pub
  cache:
    paths:
      - .pub-cache/

# ==================== BUILD ====================
build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile
        --destination plant-frontend:$CI_COMMIT_SHORT_SHA
        --no-push
        --tar-path plant-frontend-$CI_COMMIT_SHORT_SHA.tar
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        --build-arg HTTP_PROXY=$HTTP_PROXY
        --build-arg HTTPS_PROXY=$HTTPS_PROXY
  artifacts:
    paths:
      - plant-frontend-*.tar
    expire_in: 2 weeks
  only:
    - main
    - develop
