sonar.projectKey=plant-frontend
sonar.projectName=Plant Manager Frontend
sonar.sources=lib
sonar.tests=test
sonar.host.url=http://localhost:9000
sonar.login=sqp_14c2a41b6d0e79df638b80ba49ee925320b5b171
sonar.sourceEncoding=UTF-8
sonar.dart.coverage.reportPaths=coverage/lcov.info